apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80 # Service wystawia się na klastrze 
      targetPort: 8000 # port wewnątrz kontenera
  type: NodePort