apiVersion: batch/v1
kind: Job
metadata:
  name: scraper-wroclaw
  namespace: default
  labels:
    app: scraper
    city: wroclaw
spec:
  template:
    metadata:
      labels:
        app: scraper
        city: wroclaw
    spec:
      restartPolicy: OnFailure
      containers:
      - name: scraper
        image: adresowo-scraper:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: CITY
          value: "wroclaw"
        - name: PAGES
          valueFrom:
            configMapKeyRef:
              name: scraper-config
              key: wroclaw_pages
        - name: DELAY
          valueFrom:
            configMapKeyRef:
              name: scraper-config
              key: DELAY
        - name: OUTPUT_DIR
          valueFrom:
            configMapKeyRef:
              name: scraper-config
              key: OUTPUT_DIR
        volumeMounts:
        - name: data-volume
          mountPath: /data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: scraper-data-pvc
  backoffLimit: 3
  activeDeadlineSeconds: 3600  # 1 hour timeout