apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scraper

resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - job-warszawa.yaml
  - job-wroclaw.yaml
  - cronjob.yaml

commonLabels:
  app.kubernetes.io/name: adresowo-scraper
  app.kubernetes.io/version: "1.0.0"

images:
  - name: adresowo-scraper
    newTag: latest