services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - celery-network
  
  worker: 
    build: ./worker
    networks:
      - celery-network
    depends_on:
      - redis
  
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - celery-network

networks:
  celery-network:
    driver: bridge