version: "3.8"

services:
  scrapper:
    build: ./scrape
    working_dir: /app
    volumes:
      - .:/app
      - ./adresowo_descriptions:/app/adresowo_descriptions
    command: python scrape/scrape_adresowo.py
    networks:
      - rag-network
  rag-app:
    build: .
    ports:
      - "${PORT}:7860"
    env_file:
      - .env
    volumes:
      - ./adresowo_descriptions:/app/adresowo_descriptions
    command: python app.py
networks:
  rag-network:
    driver: bridge