version: '3.9'

services:
  whisper-app:
    build: .
    container_name: whisper-gradio
    ports:
      - "7860:7860"
    volumes:
      - .:/app
    working_dir: /app
    command: python app.py
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8g
    networks:
      - whisper-network

networks:
  whisper-network:
    driver: bridge